# Generated by Django 5.0 on 2023-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Application'), ('message', 'Message')], max_length=25),
        ),
    ]
